name: "Build Graphics Engine (ubuntu-latest, gcc)"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build Graphics Engine (ubuntu-latest, gcc)
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Dependencies
      run: sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config  
    - name: Configure CMake
      run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release
    - name: Upload Build Directory
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact-ubuntu-latest-gcc
        path: build
