name: Clang Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release

      - name: Build project with Clang
        run: |
          cmake --build build --config Release

      - name: Upload Build Directory for Clang-Tidy
        uses: actions/upload-artifact@v4
        with:
          name: clang-build-artifact
          path: build
