name: "clang-tidy (ubuntu-latest, clang)"
on:
  workflow_run:
    workflows: ["Build (ubuntu-latest, clang)"]
    types:
      - completed
jobs:
  lint:
    name: "clang-tidy"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Repository Artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          name: build-artifact-ubuntu-latest-clang
      - name: Extract Tar Archive
        run: tar -xvf repo.tar
      - name: Install Clang 19 and Clang-Tidy 19
        run: |
          sudo apt-get update
          sudo apt-get install -y wget lsb-release gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo apt-get install -y clang-tidy-19
      - name: Run Clang-Tidy
        run: clang-tidy-19 --checks='*,clang-analyzer-*,bugprone-*,modernize-*,readability-*,performance-*' -p build/compile_commands.json $(find GraphicsEngine/ Sandbox/ -type f \( -name "*.cpp" -o -name "*.h" \))
