name: "clang-tidy (ubuntu-latest, clang)"
on:
  workflow_run:
    workflows: ["Build (ubuntu-latest, clang)"]
    types:
      - completed
jobs:
  lint:
    name: "clang-tidy"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Build Directory
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          name: build-artifact-ubuntu-latest-clang
          path: build
      - name: Run Clang-Tidy
        run: clang-tidy -p build/compile_commands.json $(find . -name "*.cpp")
