name: Cppcheck

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run Cppcheck
        run: cppcheck --enable=all --check-level=exhaustive --suppress=missingIncludeSystem --suppress=missingInclude -i GraphicsEngine/src/glad.cpp --inconclusive --error-exitcode=1 .
