name: Deploy Doxygen Documentation

on:
  push:
    branches: [ main ]  # Runs when pushing to the main branch

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Run Doxygen
        run: doxygen Doxyfile  # Ensure your Doxyfile is correctly configured

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html  # Adjust if Doxygen outputs to a different folder
          enable_jekyll: false
          force_orphan: true
          publish_branch: gh-pages