name: "Run Unit Tests (ubuntu-latest, gcc)"
on:
  workflow_run:
    workflows: ["Build Graphics Engine (ubuntu-latest, gcc)"]
    types:
      - completed
jobs:
  test:
    name: "Run Unit Tests (ubuntu-latest, gcc)"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Build Directory
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          name: build-artifact-ubuntu-latest-gcc
          path: build
      - name: Set executable permissions for test binaries
        run: chmod +x build/bin/GraphicsEngineTests
      - name: Install Mesa3D
        run: sudo apt-get update && sudo apt-get install -y mesa-utils libgl1-mesa-dev libegl1-mesa-dev
      - name: Enable Mesa software rendering
        run: export LIBGL_ALWAYS_SOFTWARE=1
      - name: Run Tests
        working-directory: build/tests
        run: ctest --output-on-failure --build-config Release
      
